brew 'ack'
brew 'curl'
brew 'diff-so-fancy'
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'gnu-sed'
brew 'heroku'
brew 'macvim'
brew 'n'
brew 'postgresql'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'vim'
brew 'wget'
brew 'youtube-dl'
brew 'zplug'


tap 'caskroom/cask'

cask 'alfred'
cask 'atom'
cask 'bartender'
cask 'dropbox'
cask 'font-inconsolata'
cask 'google-chrome'
cask 'iterm2'
cask 'karibiner'
cask 'slack'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
