palette = "catppuccin_latte"

[character] # The name of the module we are configuring is 'character'
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'

[directory]
truncation_length = 4
# Catppuccin 'lavender'
style = "bold lavender"

[package]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

[bun]
disabled = true

[deno]
disabled = true

[elixir]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[php]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[zig]
disabled = true

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
