palette = "catppuccin_latte"

command_timeout = 5000


[kubernetes]
disabled = false
format = 'k[(\($context\))](pink) '

[openstack]
disabled = true

[os]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[java]
disabled = true

[helm]
disabled = true

[gcloud]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[buf]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

[bun]
disabled = true

[deno]
disabled = true

[elixir]
disabled = true

[golang]
disabled = true

[php]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[zig]
disabled = true


[directory]
truncation_length = 8
# Catppuccin 'lavender'
style = "semibold overlay0"

[character]
success_symbol = "[Λ](crust)"
error_symbol = "[Λ](pink)"
vimcmd_symbol = "[Λ](crust)"

[git_branch]
format = "[$branch]($style)"
style = "flamingo"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "lavender"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "(stash)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "crust"

[cmd_duration]
format = "[$duration]($style) "
style = "overlay2"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"


# Pure prompt
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""
