require("plugins")
require("autocmd")
require("settings")
require("commands")
require("lsp")
require("snippets")

-- Plugin Configs
require("_navigator")
require("_cmp")
require("_treesitter")
require("_telescope")
require("_tree")
require("_lualine")
require("_autopairs")
require("_Comment")
require("_null-ls")
require("_fidget")

require("mappings")
