#!/usr/bin/env sh

# mission-control desktop labels
yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label notes
yabai -m space 4 --label social
yabai -m space 5 --label media
yabai -m space 6 --label misc

# window rules
yabai -m rule --add app="^Brave Browser$" space=web
yabai -m rule --add app="^Ghostty$" space=code
yabai -m rule --add app="^Notes$" space=notes
yabai -m rule --add app="^Obsidian$" space=notes
yabai -m rule --add app="^Mail$" space=social
yabai -m rule --add app="^Calendar$" space=social
yabai -m rule --add app="^Signal$" space=social
yabai -m rule --add app="^Discord$" space=social
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^Transmission$" space=misc

yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility|System Settings|Karabiner-Elements|Finder)$" manage=off

# specific space settings
yabai -m config --space mail layout stack

# global settings
yabai -m config \
	external_bar all:41:0 \
	mouse_follows_focus on \
	focus_follows_mouse off \
	window_placement second_child \
	window_topmost off \
	window_shadow on \
	window_animation_duration 0.25 \
	window_opacity_duration 0.25 \
	active_window_opacity 0.95 \
	normal_window_opacity 0.10 \
	window_opacity on \
	insert_feedback_color 0xaad75f5f \
	active_window_border_color 0xBF775759 \
	normal_window_border_color 0x7f353535 \
	window_border_width 4 \
	window_border_radius 12 \
	window_border_blur on \
	window_border_hidpi on \
	window_border on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 8 \
	left_padding 8 \
	right_padding 8 \
	bottom_padding 8 \
	window_gap 10 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# completely disable the mac menu bar
# yabai -m config menubar_opacity 0.0

echo "yabai configuration loaded.."
