vim.api.nvim_create_user_command("Light", "set background=light", {})
vim.api.nvim_create_user_command("Dark", "set background=dark", {})
vim.api.nvim_create_user_command("SnipSource", "<cmd>source ~/.config/nvim/after/plugin/luasnip.lua<CR>", {})
vim.api.nvim_create_user_command("CopyFilename", function()
	local path = vim.fn.expand("%")
	vim.fn.setreg("+", path)
	vim.notify('Copied "' .. path .. '" to the clipboard!')
end, {})
local p = require("plenary.path")
