return {
  'nvim-treesitter/nvim-treesitter',
  event = { 'BufReadPre', 'BufNewFile' },
  cmd = { 'TSUpdate', 'TSInstall' },
  dependencies = {
    {
      'nvim-treesitter/nvim-treesitter-textobjects',
      event = { 'BufReadPre', 'BufNewFile' },
      cmd = { 'TSUpdate', 'TSInstall' },
    },
  },
  build = ':TSUpdate',
  opts = {
    -- Add languages to be installed here that you want installed for treesitter
    ensure_installed = {
      'bash',
      'c',
      'cmake',
      'cpp',
      'css',
      'dockerfile',
      'git_config',
      'git_rebase',
      'gitcommit',
      'gitignore',
      'go',
      'gomod',
      'gosum',
      'gotemplate',
      'gowork',
      'hack',
      'helm',
      'hlsl',
      'html',
      'javascript',
      'json',
      'json5',
      'lua',
      'luadoc',
      'make',
      'markdown',
      'markdown_inline',
      'php',
      'proto',
      'python',
      'regex',
      'rust',
      'tmux',
      'toml',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'yaml',
      'zig',
    },

    -- Autoinstall languages that are not installed. Defaults to false (but you can change for yourself!)
    auto_install = true,
    -- Install languages synchronously (only applied to `ensure_installed`)
    sync_install = false,
    -- List of parsers to ignore installing
    ignore_install = {},
    -- You can specify additional Treesitter modules here: -- For example: -- playground = {--enable = true,-- },
    modules = {},
    highlight = { enable = true },
    indent = { enable = true },
  },
}
