. /opt/homebrew/opt/asdf/libexec/asdf.sh
ZSH_DISABLE_COMPFIX=true

eval "$(starship init zsh)"

export DOTFILES="$HOME/dotfiles"
export ZSH=$HOME/.oh-my-zsh
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=~/.composer/vendor/bin:$PATH

# execute locally installed npm modules
export PATH="./node_modules/.bin:$PATH"
# put things in ~/.bin into my $PATH
export PATH="$HOME/.bin:$PATH"

TZ="Europe/London"
HISTFILE=$HOME/.zhistory
HISTSIZE=20000
SAVEHIST=20000
setopt HIST_IGNORE_SPACE
HOSTNAME="`hostname`"
PAGER='less'
export AUTOENV_FILE_ENTER=".env"
DEFAULT_USER="t"
unsetopt correct
unsetopt correctall
DISABLE_CORRECTION="true"

GIT_MERGE_AUTOEDIT=no
export GIT_MERGE_AUTOEDIT

# the one true way
export EDITOR='nvim'
export VEDITOR='code'
export TERM=xterm-256color

plugins=(git npm macos tmux tig vagrant node colored-man-pages docker fzf laravel yarn fancy-ctrl-z zsh-autosuggestions zsh-syntax-highlighting)
typeset -A ZSH_HIGHLIGHT_STYLES
# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md
ZSH_HIGHLIGHT_STYLES[alias]='fg=113'
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[globbing]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='none'

# so autoenv runs all the time, even when you open a tmux split
cd .

source $ZSH/oh-my-zsh.sh
source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/functions

#FZF
# Setting ag as the default source for fzf
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# bun completions
[ -s "/Users/t/.bun/_bun" ] && source "/Users/t/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

[ -f $HOME/dotfiles/zsh/work ] && source $HOME/dotfiles/zsh/work
