return {
  'lukas-reineke/indent-blankline.nvim',
  event = 'BufReadPost',
  main = 'ibl',
  opts = {
    scope = {
      show_start = false,
    },
    exclude = {
      filetypes = {
        'startify',
        'dashboard',
        'dotooagenda',
        'log',
        'fugitive',
        'gitcommit',
        'packer',
        'vimwiki',
        'markdown',
        'json',
        'txt',
        'vista',
        'help',
        'todoist',
        'NvimTree',
        'peekaboo',
        'git',
        'TelescopePrompt',
        'undotree',
        'org',
        'flutterToolsOutline',
        'qf',
      },
    },
  },
}
